-- Add new columns to contact_agent_memory for agent learning capabilities
ALTER TABLE public.contact_agent_memory ADD COLUMN IF NOT EXISTS memory_summary TEXT;
ALTER TABLE public.contact_agent_memory ADD COLUMN IF NOT EXISTS topics TEXT[] DEFAULT '{}';
ALTER TABLE public.contact_agent_memory ADD COLUMN IF NOT EXISTS conversation_count INTEGER DEFAULT 0;
ALTER TABLE public.contact_agent_memory ADD COLUMN IF NOT EXISTS last_learning_at TIMESTAMPTZ;
ALTER TABLE public.contact_agent_memory ADD COLUMN IF NOT EXISTS knowledge_sources JSONB DEFAULT '[]';

-- Create index for faster topic-based searches
CREATE INDEX IF NOT EXISTS idx_contact_agent_memory_topics ON public.contact_agent_memory USING GIN(topics);

-- Add comments for documentation
COMMENT ON COLUMN public.contact_agent_memory.memory_summary IS 'Condensed knowledge summary about the contact, generated by the agent';
COMMENT ON COLUMN public.contact_agent_memory.topics IS 'Keywords/topics associated with this contact for quick matching';
COMMENT ON COLUMN public.contact_agent_memory.conversation_count IS 'Number of conversations the agent has had about this contact';
COMMENT ON COLUMN public.contact_agent_memory.last_learning_at IS 'Timestamp of last agent learning/update';
COMMENT ON COLUMN public.contact_agent_memory.knowledge_sources IS 'List of data sources used for agent knowledge';